version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    # Specify additional file patterns to check.
    # By default, Dependabot looks for build.gradle(.kts) files.
    # To include gradle.properties, add it to the file patterns.
    # file-patterns:
    #   - "**/build.gradle"
    #   - "**/build.gradle.kts"
    #   - "**/gradle.properties"
    # or to make it simpler, use a wildcard to get all gradle files
    file-patterns:
      - "**/*.gradle*"
      - "**/gradle.properties"
